//ok
POST http://localhost:8080/api/admin/usermanagement
token: 0664a7413852db420f512fe57cf214b71d342bdc260068eec1c24fe83f0888d36a6d3f17a46a84fa5fccbce23ccb79b8
Content-Type: application/json

{
  "phone": "139556",
  "name": "宏",
  "password":"123456",
  "authority": "1",
  "post": "教授"
}

###
//ok
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "phone": "15546309816",
  "password": "123456"
}

###
//ok
POST http://localhost:8080/api/admin/register
Content-Type: application/json

{
  "phone": "15546309816",
  "name": "白欣",
  "password":"123456",
  "authority": "2"
}

###
//ok
POST http://localhost:8080/api/admin/modify
Content-Type: application/json

{
  "phone": "15546309826",
  "name": "白欣宇",
  "password":"123456",
  "authority": "1"
}

###
//ok
POST http://localhost:8080/api/admin/removeadmin
Content-Type: application/json


{
  "phone": "1044919284177"
}

###
//ok
POST http://localhost:8080/api/admin/addhomework
token: 0664a7413852db420f512fe57cf214b71d342bdc260068eec1c24fe83f0888d36a6d3f17a46a84fa5fccbce23ccb79b8
Content-Type: application/json


{
  "content": "fgfhgj",
  "teacher": {
  "id": "3"
  },
  "title": "紧急",
  "deadLineTime": "2014-01-02 15:00"
}
###
###
//ok
POST http://localhost:8080/api/admin/modifyhomework
Content-Type: application/json


{
  "id": "1",
  "content": "回复信息牛逼",
  "teacher": {
    "id": "3"
  },
  "title": "不紧急",
  "deadLineTime": "2014-01-02 15:00"
}
###
//ok
POST http://localhost:8080/api/admin/closehomework
Content-Type: application/json

{
  "id": "1"
}
###
###
//ok
POST http://localhost:8080/api/admin/ExamInfo
Content-Type: application/json

{
  "beginTime": "2019-06-23 15:00",
  "endTime": "2019-06-23 17:00",
  "classRoom": "911",
  "className": "SOB"
}
###
###
//ok
POST http://localhost:8080/api/admin/ExamInfo/updateteacher
Content-Type: application/json

{
  "id": "1",
  "teacher": {
  "id": "5"
  }
}
###
###
//??
GET http://localhost:8080/api/admin/ExamInfo/findExamInfo

###
###
//??
POST http://localhost:8080/api/admin/ExamInfo/getExamInfo
Content-Type: application/json

{
  "classRoom":"910"
}
###